/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.eci.arsw.Cliente;

import edu.eci.arsw.CalendarioComun.TColaborativa;
import edu.eci.arsw.CalendarioComun.TInformativa;
import static edu.eci.arsw.Cliente.Calendario.calendario;

/**
 *
 * @author 2085941
 */
public class DatosTareas extends javax.swing.JFrame {

    /**
     * Creates new form DatosTareas
     */
    public DatosTareas() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setSize(415, 415);
        setResizable(false);
        
    }

    DatosTareas(TColaborativa tc) {
        initComponents();
        nomTarea.setText(tc.getNombre());
        descTarea.setText(tc.getDescripcion());
        tipo.setText("Colaborativa");
        dia.setText(tc.getFecha().getDia()+"");
        mes.setText(tc.getFecha().getMes()+"");
        anio.setText(tc.getFecha().getAnio()+"");
    }

    DatosTareas(TInformativa ti) {
        initComponents();
        nomTarea.setText(ti.getNombre());
        descTarea.setText(ti.getDescripcion());
        tipo.setText("Informativa");
        dia.setText(ti.getFecha().getDia()+"");
        mes.setText(ti.getFecha().getMes()+"");
        anio.setText(ti.getFecha().getAnio()+"");
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomTarea = new javax.swing.JLabel();
        descTarea = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        mes = new javax.swing.JLabel();
        anio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("Nombre de la tarea");

        jLabel2.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 153));
        jLabel2.setText("Descripción de la tarea ");

        jLabel3.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 153));
        jLabel4.setText("Día");

        jLabel5.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 153));
        jLabel5.setText("Mes ");

        jLabel6.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 153));
        jLabel6.setText("Año");

        nomTarea.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        nomTarea.setForeground(new java.awt.Color(102, 0, 102));
        nomTarea.setText("       ");

        descTarea.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        descTarea.setForeground(new java.awt.Color(102, 0, 102));
        descTarea.setText("      ");

        dia.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        dia.setForeground(new java.awt.Color(102, 0, 102));
        dia.setText("       ");

        mes.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        mes.setForeground(new java.awt.Color(102, 0, 102));
        mes.setText("     ");

        anio.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        anio.setForeground(new java.awt.Color(102, 0, 102));
        anio.setText("        ");

        jLabel7.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 153));
        jLabel7.setText("Tipo de la tarea");

        tipo.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        tipo.setForeground(new java.awt.Color(102, 0, 102));
        tipo.setText("       ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomTarea))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(descTarea)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(62, 62, 62)
                                .addComponent(tipo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(dia))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(anio)
                                .addComponent(mes)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomTarea)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descTarea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tipo))
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(anio))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anio;
    private javax.swing.JLabel descTarea;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mes;
    private javax.swing.JLabel nomTarea;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
